A cycle-values video-aspect-override "16:9" "4:3" "2:1" "2.21:1" "2.35:1" "2.39:1" "1.6:1"
alt+LEFT add audio-delay -0.05 ; show-text "Аудио задержка: ${audio-delay}" 3000
alt+RIGHT add audio-delay +0.05 ; show-text "Аудио задержка: ${audio-delay}" 3000
alt+DOWN add sub-delay -0.05  ; show-text "Субтитров задержка: ${sub-delay}" 3000
alt+UP add sub-delay +0.05 ; show-text "Субтитров задержка: ${sub-delay}" 3000
j show-text sub-file-paths ; cycle sub  ; show_text ${track-list}${current-tracks/sub/external-filename:${sid}} 3000
a show-text sub-file-paths ; cycle audio  ; show_text ${track-list}${current-tracks/audio/external-filename:${aid}} 3000








ctrl+z set sub-border-size 1.65
ctrl+x add sub-border-size +0.5
x add sub-pos +1
z add sub-pos -1
Shift+x add sub-scale +0.05
Shift+z add sub-scale -0.05




alt+1 add contrast -1
alt+2 add contrast 1
alt+3 add brightness -1
alt+4 add brightness 1
alt+5 add gamma -1
alt+6 add gamma 1
alt+7 add saturation -1
alt+8 add saturation 1
Alt+= add video-zoom   0.1
Alt+- add video-zoom  -0.1
alt+9 add panscan 0.1
alt+0 add panscan -0.1





Shift+F5 script-message reset-all
TAB script-binding stats/display-page-4
q script-binding quality_menu/video_formats_toggle
t script-message-to seek_to toggle-seeker









j show-text sub-file-paths ; cycle sub
Ctrl+1 playlist-prev
Ctrl+2 playlist-next

. frame-step ; show-text ${estimated-frame-number}/${estimated-frame-count}
, frame-back-step ; show-text ${estimated-frame-number}/${estimated-frame-count}
m no-osd cycle mute ; no-osd cycle sub-visibility ; show-text ${sub-visibility}





DOWN playlist-prev
SPACE cycle pause
UP playlist-next
#u cycle-values sub-ass-style-overrides force yes


E ignore
W ignore
I ignore
i script-binding stats/display-stats-toggle
1 ignore
2 ignore
3 ignore
4 ignore
5 ignore
6 ignore
7 ignore
8 ignore
e ignore
w ignore
Shift+# ignore
r ignore
MBTN_MID ignore
F8 ignore
F9 ignore
WHEEL_UP      ignore
WHEEL_DOWN   ignore
Ctrl+Shift+LEFT ignore
Ctrl+Shift+RIGHT ignore
Ctrl+LEFT ignore
Ctrl+RIGHT ignore
