# meow

# paths
screenshot-dir = ~~/Pictures/screenshots/mpv

# ui
title = ${filename}
osd-on-seek = no
keep-open = yes
osd-font-size = 30
osd-border-size = 0.5
force-media-title
write-filename-in-watch-later-config
osd-duration = 3000 # 3s
osd-playing-msg = [${playlist-pos-1}/${playlist-count}]
osd-playing-msg = ${osd-ass-cc/0}{\\an9}[${playlist-pos-1}/${playlist-count}]
osc = no

# video
video-sync = audio
priority = high
video-output-levels = full
hwdec = auto
tone-mapping = bt.2446a
vo = gpu-next
hdr-compute-peak = auto
hr-seek = yes
scale = lanczos
dscale = lanczos
cscale = lanczos
dither = no

# screenshots
screenshot-format = png
screenshot-png-compression = 1
screenshot-png-filter = 5
screenshot-tag-colorspace = yes
screenshot-high-bit-depth = no
screenshot-template = mpv_%F_%p_%04n

# audio
alang = jap,jp
audio-file-auto = fuzzy
audio-file-paths = **
audio-channels = auto-safe
ao = wasapi
ad-lavc-downmix = no
volume-max = 150
ad-lavc-threads = 0

# subs
slang = rus,ru
sub-ass-vsfilter-color-compat = full
sub-auto = fuzzy
sub-file-paths = **
sub-border-size = 2
sub-blur = 1

# cache
cache = yes
cache-secs = 10
